/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

pub fn euler_2(limit: i32) -> i32 {
    let mut i: i32 = 1;
    let mut j: i32 = 2;
    let mut sum: i32 = 2;
    loop {
        let temp: i32 = i;
        i = j;
        j = j + temp;
        if j % 2 == 0{
            sum += j;
        }
        if j >= limit {
            break;
        }
    }
    return sum;
}
